#!/bin/bash

echo "Watch what happens without declare -A..."

#declare -A myArray
myArray[i]=one
myArray[ii]=two
myArray[iii]=three
myArray[iv]=four
myArray[v]=five
echo ${myArray[i]} ${myArray[ii]} ${myArray[iii]} ${myArray[iv]} ${myArray[v]}

#declare -A myArrayWik
myArrayWik=([I]=ONE [II]=TWO [III]=THREE [IV]=FOUR [V]=FIVE)
echo "${myArrayWik[I]} [I]"
echo "${myArrayWik[II]} [II]"
echo "${myArrayWik[III]} [III]"
echo "${myArrayWik[IV]} [IV]"
echo "${myArrayWik[V]} [V]"

echo "Also, index IDs don't work with these associative arrays..."
echo "${myArrayWik[2]} [2]"
echo "${myArray[1]} [1]"
echo "${myArrayWik[0]} [0]"
