#!/bin/bash

varfunction() {
VarA="apricots"
VarB="berries"

echo "function VarA = $VarA"
echo "function VarB = $VarB"
}

VarA="apples"
VarB="bananas"

echo "
Set variables:"
echo "script VarA = $VarA"
echo "script VarB = $VarB"

echo "
Call function:"
varfunction

echo "
Final Countdown:"
echo "final VarA = $VarA"
echo "final VarB = $VarB"