#!/bin/bash

varfunction() {
local VarA="apricots"
VarB="berries"

echo "function VarA = $VarA"
echo "function VarB = $VarB"
}

VarA="apples"
VarB="bananas"

echo "script VarA = $VarA"
echo "script VarB = $VarB"

varfunction

echo "script VarA = $VarA"
echo "script VarB = $VarB"
