#!/bin/bash

# Create a simple echo function
echofunction() {
echo "First function"
}

# Call the simple echo function
echo "Running echofunction..."
echofunction


# Show the "return" code
echo "Return code: $?"

# Create a multi-return code function
# This will "return" the first argument of the function
returnfunction() {
return $1
}

# Call the multi-return code function as "1"
echo "Running returnfunction 1..."
returnfunction 1

# Show the "return" code
echo "Return code: $?"

# Call the multi-return code function as "2"
echo "Running returnfunction 2..."
returnfunction 2

# Show the "return" code
echo "Return code: $?"

# Call the multi-return code function as "3"
echo "Running returnfunction 3..."
returnfunction 3

# Show the "return" code
echo "Return code: $?"

# Call the multi-return code function as "apples"
echo "Running returnfunction apples..."
returnfunction apples

# Show the "return" code
echo "Return code: $?"
