#!/bin/bash

echofunction() {
echo "First function"
}

echo "Running echofunction..."
echofunction

echo "Return code: $?"

returnfunction() {
return $1
}

echo "Running returnfunction 1..."
returnfunction 1

echo "Return code: $?"

echo "Running returnfunction 2..."
returnfunction 2

echo "Return code: $?"

echo "Running returnfunction 3..."
returnfunction 3

echo "Return code: $?"

echo "Running returnfunction apples..."
returnfunction apples

echo "Return code: $?"
