#!/bin/bash

IFS=$'\t' # Use the $IFS variable to define a "loopable" field as "each" new line"

for EveryTAB in $(cat randomlooped); do

echo "IFS_tab_ $EveryTAB"

done

unset IFS # We don't want our strange settings messing with other things.
