#!/bin/bash

IFS=$'\n'

for EveryLine in $(cat countfile); do

Random_string="$(pwgen -s -1 8)"

echo "$EveryLine" | sed "s/add2end/IFS_$Random_string/"
echo "$EveryLine" | sed "s/add2end/IFS_$Random_string/" >> randomlooped

done

unset IFS
