#!/bin/bash

IFS=$'\n'

for EveryLine in $(cat countfile); do

RANDOM_string="$(pwgen -s -1 8)"

echo "$EveryLine" | sed "s/add2end/IFS_$RANDOM_string/"
echo "$EveryLine" | sed "s/add2end/IFS_$RANDOM_string/" >> randomlooped

done

unset IFS
