#!/bin/sh

_5=5
_6=6

echo "Trying Shell flags..."
if [ $_5 -lt $_6 ]; then
echo "Less than! It works!"
fi

echo "Trying BASH operators..."
if (( $_5 < $_6 )); then
echo "Less than! It works!"
fi

echo "Trying BASH operators..."
if [[ $_5 < $_6 ]]; then
echo "Less than! It works!"
fi

