#!/bin/bash

VARIABLE="vip"

# Shell:
echo "Trying Shell..."
if [ $VARIABLE = vip ]; then
echo "No quotes! It works!"
fi

# BASH:
echo "Trying BASH..."
if [ "$VARIABLE" = "vip" ]; then
echo "Quotes It works!"
fi
