#!/bin/sh

echo "No variable, simply stating \"true\""
true && echo "AND/OR is true." || echo "AND/OR is false."
true && echo "AND is true."
true || echo "OR is false."

echo "No variable, simply stating \"false\""
false && echo "AND/OR is true." || echo "AND/OR is false."
false && echo "AND is true."
false || echo "OR is false."

