#!/bin/sh

echo "No variable, simply stating \"true\""
true && echo "And/Or is true." || echo "And/Or is false."
true && echo "And is true."
true || echo "Or is false."

echo "No variable, simply stating \"false\""
false && echo "And/Or is true." || echo "And/Or is false."
false && echo "And is true."
false || echo "Or is false."
