#!/bin/sh

Var=true
echo "Variable set to: $Var"

$Var && echo "And/Or is true." || echo "And/Or is false."
$Var && echo "And is true."
$Var || echo "Or is false."

Var=false
echo "Variable set to: $Var"

$Var && echo "And/Or is true." || echo "And/Or is false."
$Var && echo "And is true."
$Var || echo "Or is false."
