#!/bin/sh

VAR=true
echo "Variable set to: $VAR"

# Simple test:
$VAR && echo "AND/OR is true." || echo "AND/OR is false."
$VAR && echo "AND is true."
$VAR || echo "OR is false."

VAR=false
echo "Variable set to: $VAR"

# Same simple test:
$VAR && echo "AND/OR is true." || echo "AND/OR is false."
$VAR && echo "AND is true."
$VAR || echo "OR is false."

