#!/bin/sh

VAR=apples
echo "Variable set to: $VAR"

$VAR && echo "AND/OR is true." || echo "AND/OR is false."
$VAR && echo "AND is true."
$VAR || echo "OR is false."

VAR=pencils
echo "Variable set to: $VAR"

$VAR && echo "AND/OR is true." || echo "AND/OR is false."
$VAR && echo "AND is true."
$VAR || echo "OR is false."

