#!/bin/sh

echo "
Arguments entered via \$@ ..."
./varargs $@

echo "
Arguments entered via \$(echo \$@) ..."
./varargs $(echo $@)

echo "
Arguments entered via \$* ..."
./varargs $*

echo "
Arguments entered via \$(echo \$*) ..."
./varargs $(echo $*)
