#!/bin/bash

myVAR="Pineapple pie"

echo "without quotes:"
echo $9
echo $10
echo $11
echo $12
echo $myVAR

echo "with quotes:"
echo "$9"
echo "$10"
echo "$11"
echo "$12"
echo "$myVAR"

echo "{brackets} without quotes:"
echo ${9}
echo ${10}
echo ${11}
echo ${12}
echo ${myVAR}

echo "{brackets} with quotes:"
echo "${9}"
echo "${10}"
echo "${11}"
echo "${12}"
echo "${myVAR}"
