#!/bin/sh

TrueSQ='true'
TrueDQ="true"
TrueVar=true
FalseSQ='false'
FalseDQ="false"
FalseVar=false

if $TrueSQ ; then
    echo TrueSQ $TrueSQ
else
    echo FAIL $FalseDQ
fi

if $TrueDQ ; then
    echo TrueDQ $TrueDQ
else
    echo FAIL $FalseDQ
fi

if $TrueVar ; then
    echo TrueVar $TrueVar
else
    echo FAIL $FalseDQ
fi

if $FalseSQ ; then
    echo FalseSQ
else
    echo FAIL $FalseSQ
fi

if $FalseDQ ; then
    echo FalseDQ
else
    echo FAIL $FalseDQ
fi

if $FalseVar ; then
    echo FalseVar
else
    echo FAIL $FalseVar
fi
