#!/bin/sh

echo "1. \$Var is NOT yet set!"

if [ -n "$Var" ]; then
echo "NOT empty set: $Var"
else
echo "IS empty set: $Var"
fi

Var=varSet
echo "2. \$Var has been set!"

if [ -n "$Var" ]; then
echo "NOT empty set: $Var"
else
echo "IS empty set: $Var"
fi

unset Var
echo "3. \$Var has been UNset!"

if [ -n "$Var" ]; then
echo "NOT empty set: $Var"
else
echo "IS empty set: $Var"
fi
