#!/bin/sh

echo "1. \$VAR is NOT yet set!"

if [ -z "$VAR" ]; then
echo "NOT set: $VAR"
else
echo "IS set: $VAR"
fi

VAR=varSet
echo "2. \$VAR has been set!"

if [ -z "$VAR" ]; then
echo "NOT set: $VAR"
else
echo "IS set: $VAR"
fi

unset VAR
echo "3. \$VAR has been UNset!"

if [ -z "$VAR" ]; then
echo "NOT set: $VAR"
else
echo "IS set: $VAR"
fi
