#!/bin/sh

echo "1. \$Var is NOT yet set!"

if [ -z "$Var" ]; then
echo "NOT set: $Var"
else
echo "IS set: $Var"
fi

Var=varSet
echo "2. \$Var has been set!"

if [ -z "$Var" ]; then
echo "NOT set: $Var"
else
echo "IS set: $Var"
fi

unset Var
echo "3. \$Var has been UNset!"

if [ -z "$Var" ]; then
echo "NOT set: $Var"
else
echo "IS set: $Var"
fi
