#!/bin/sh

echo "1. \$VAR is NOT yet set!"

if [ -n "$VAR" ]; then
echo "NOT empty set: $VAR"
else
echo "IS empty set: $VAR"
fi

VAR=varSet
echo "2. \$VAR has been set!"

if [ -n "$VAR" ]; then
echo "NOT empty set: $VAR"
else
echo "IS empty set: $VAR"
fi

unset VAR
echo "3. \$VAR has been UNset!"

if [ -n "$VAR" ]; then
echo "NOT empty set: $VAR"
else
echo "IS empty set: $VAR"
fi
